trigger:
  - main

pr:
  - main

name: $(BuildID)-$(SourceBranchName)

resources:
  repositories:
    - repository: self
      type: git
      ref: main

jobs:
  - job: Server
    displayName: Web API
    pool:
      vmImage: ubuntu-latest

    steps:
      - checkout: self
        clean: true

      - task: PowerShell@2
        displayName: Swap config files
        inputs:
          targetType: inline
          script: >
            Copy-Item "Server/WebApi/appsettings.Token.json" -Destination "Server/WebApi/appsettings.json" -Force

            Remove-Item "Server/WebApi/appsettings.Token.json" -Force

      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: Update configurations
        inputs:
          rootDirectory: Server
          targetFiles: '**\*appsettings.json'
          escapeType: none
          tokenPrefix: __
          tokenSuffix: __

      - task: UseDotNet@2
        displayName: Use .Net SDK 7.x
        continueOnError: True
        inputs:
          version: 7.x

      - task: DotNetCoreCLI@2
        displayName: dotnet restore
        inputs:
          command: restore
          projects: Server/**/*.csproj

      - task: DotNetCoreCLI@2
        displayName: dotnet publish
        inputs:
          command: publish
          publishWebProjects: false
          projects: Server/**/*.csproj
          arguments: -c Release -o $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        displayName: Save artifacts

  - job: Client
    displayName: Website
    pool:
      vmImage: ubuntu-latest

    steps:
      - checkout: self
        clean: true

      - task: UseNode@1
        displayName: Use Node 18.x
        inputs:
          version: 18.18.x

      - task: Npm@1
        displayName: Install packages
        inputs:
          command: 'install'
          workingDir: 'Client'

      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: Update GA tag
        inputs:
          rootDirectory: "Client/src"
          targetFiles: "**/index.html"
          escapeType: none
          tokenPrefix: __
          tokenSuffix: __

      - task: Npm@1
        displayName: Build
        inputs:
          command: custom
          workingDir: Client
          verbose: false
          customCommand: run build.prod

      - task: ArchiveFiles@2
        displayName: Stage artifacts
        inputs:
          rootFolderOrFile: Client/dist/app
          includeRootFolder: false
          archiveFile: $(Build.ArtifactStagingDirectory)/Website.zip

      - task: PublishBuildArtifacts@1
        displayName: Save artifacts
