packages:
  - libs/chartjs-financial
  - libs/indy-charts
  - client
  - tests/playwright
  - tests/vitepress

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract
  - unrs-resolver
  - vue-demi
