packages:
  - libs/chartjs-financial
  - libs/indy-charts
  - client
  - tests/playwright
  - tests/vitepress

minimumReleaseAge: 0
minimumReleaseAgeStrict: false

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  unrs-resolver: false
  vue-demi: false
