name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - User Interface/Experience
        - New Technical Indicator
        - Chart Functionality
        - API Enhancement
        - Performance Improvement
        - Documentation
        - Developer Experience
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my workflow
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help you.
      placeholder: Explain how you would use this feature and what benefits it would provide.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request here.
      placeholder: Any additional information, links, or examples...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I understand this is a demo project and complex features may not be implemented
          required: true
        - label: This feature request is appropriate for the stock charts demo scope
          required: true