name: Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? Please search existing issues first to see if it's already been answered.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Setup and Installation
        - Usage and Configuration
        - Technical Indicators
        - Chart Functionality
        - Development and Contributing
        - Architecture and Design
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide any additional context that might help answer your question.
      placeholder: Any relevant background information...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the documentation and README
          required: true